trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    include:
    - src/*
    - tool/*
    - azure-pipelines.yml

pr:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*
    - README.md
    - .dependabot/*
    - .editorconfig

resources:
  repositories:
  - repository: templates
    type: github
    name: unmango/azure-pipelines-templates
    endpoint: unmango

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  Pool: Linux
  GitHubConnection: 'UnMango GitHub NuGet'
  BuildConfiguration: Release
  ArtifactName: Packages
  CI: true

stages:
- stage: build
  displayName: Build, Test, and Pack
  jobs:
  - template: /jobs/dotnet/nuget-package.yml@templates
    parameters:
      pool: $(Pool)
      projects: src/**/*.csproj
      nugetConfig: NuGet.Config
      externalFeedCredentials: $(GitHubConnection)
      artifactName: $(ArtifactName)

      postBuild:
      - template: /steps/dotnet/test.yml
        parameters:
          buildProjects: false
          installReportGenerator: false

- stage: deploy
  displayName: Deploy to GitHub
  condition: contains(variables['Build.SourceBranch'], 'master')
  jobs:
  - template: /jobs/nuget/push.yml@templates
    parameters:
      pool: $(Pool)
      environment: GitHub
      feed: $(GitHubConnection)
      artifact: $(ArtifactName)
