version: 1

update_configs:
- package_manager: dotnet:nuget
  directory: "/src/UnMango.Proxmox.Client"
  update_schedule: live
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:minor

# - package_manager: dotnet:nuget
#   directory: "/test/UnMango.Proxmox.Client.Tests"
#   update_schedule: live
#   automerged_updates:
#   - match:
#       dependency_type: all
#       update_type: semver:minor
